# Server
server.port=8761

# Application name
spring.application.name=eureka-server

# Eureka config
# Ye server khud ko register nahi karega
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Eureka dashboard
eureka.server.enable-self-preservation=false

# Logging
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO
